tenant-a:
- name: TENANT-A
  mac_vrf_vni_base: 10000
  vrfs:
  - name: VRF10
    vrf_vni: 10
    vtep_diagnostic:
      loopback: 10
      loopback_ip_range: 10.255.10.0/27
    svis:
    - id: 11
      name: VRF10_VLAN11
      enabled: true
      ip_address_virtual: 10.10.11.1/24
    - id: 12
      name: VRF10_VLAN12
      enabled: true
      ip_address_virtual: 10.10.12.1/24
    - id: 5
      name: '5'
      ip_address: 10.10.5.1/24
    - id: 15
      name: VRF10_VLAN15
      ip_address: 10.10.15.1/24
      enabled: true
    - id: 300
      name: vlan_300
      ip_address: 10.30.10.1/24
      enabled: true
    - id: 50
      name: vlan_50
      ip_address: 10.10.50.1/24
      enabled: true
  - name: VRF11
    vrf_vni: 11
    vtep_diagnostic:
      loopback: 11
      loopback_ip_range: 10.255.11.0/27
    svis:
    - id: 21
      name: VRF11_VLAN21
      enabled: true
      ip_address_virtual: 10.10.21.1/24
    - id: 22
      name: VRF11_VLAN22
      enabled: true
      ip_address_virtual: 10.10.22.1/24
    - id: 60
      name: VRF11_VLAN60
      ip_address: 10.10.60.1/24
      enabled: true
  - name: VRF12
    vrf_vni: 12
    svis:
    - id: 31
      name: VRF12_VLAN31
      ip_address: 10.10.31.1/24
      enabled: true
    - id: 45
      name: VRF12_VLAN45
      ip_address: 10.10.45.1/24
      enabled: true
  
  l2vlans:
  - id: 3401
    name: L2_VLAN3401
  - id: 3402
    name: L2_VLAN3402
